services:
  rekrutai-fe:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rekrutai-frontend
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
    env_file:
      - .env.local
    restart: unless-stopped
    networks:
      - rekrutai-network

networks:
  rekrutai-network:
    driver: bridge
