// import { TWorkExperience } from "@/shared/api/types/resume";
import { TUser } from "@/shared/api/types/user";
import { TPublicVacancy } from "./types";

export const mockUser: TUser = {
  id: 1,
  name: "Иванов Иван",
  email: "test@mail.com",
};

// export const workExperiences: TWorkExperience[] = [
//   {
//     id: 1,
//     cv_id: 101,
//     title: "Frontend Developer",
//     company: "Tech Solutions Ltd.",
//     city: "Berlin",
//     post: "React Developer",
//     description:
//       "Разработка веб-приложений с использованием React и Next.js. Разработка веб-приложений с использованием React и Next.js.",
//     // created_at: "2021-06-15T12:00:00.000Z",
//     // updated_at: "2023-04-10T14:30:00.000Z",
//     start_at: "2020-09-01T00:00:00.000Z",
//     end_at: "2022-12-31T00:00:00.000Z",
//     // deleted_at: null,
//     // cv: null,
//   },
//   {
//     id: 2,
//     cv_id: 102,
//     title: "Frontend Engineer",
//     company: "InnovateX",
//     city: "Amsterdam",
//     post: "Vue.js Developer",
//     description:
//       "Создание UI-компонентов и оптимизация производительности приложений.",
//     // created_at: "2022-01-20T10:15:00.000Z",
//     // updated_at: "2024-02-05T09:45:00.000Z",
//     start_at: "2021-05-10T00:00:00.000Z",
//     end_at: null, // текущее место работы
//     // deleted_at: null,
//     // cv: null,
//   },
//   {
//     id: 3,
//     cv_id: 103,
//     title: "Junior Frontend Developer",
//     company: "WebCraft",
//     city: "Warsaw",
//     post: "JavaScript Developer",
//     description: "Поддержка и разработка клиентских интерфейсов.",
//     // created_at: "2019-11-30T08:20:00.000Z",
//     // updated_at: "2021-08-17T15:10:00.000Z",
//     start_at: "2019-03-15T00:00:00.000Z",
//     end_at: "2020-08-31T00:00:00.000Z",
//     // deleted_at: null,
//     // cv: null,
//   },
//   {
//     id: 4,
//     cv_id: 101,
//     title: "Frontend Developer",
//     company: "Tech Solutions Ltd.",
//     city: "Berlin",
//     post: "React Developer",
//     description:
//       "Разработка веб-приложений с использованием React и Next.js. Разработка веб-приложений с использованием React и Next.js.",
//     created_at: "2021-06-15T12:00:00.000Z",
//     updated_at: "2023-04-10T14:30:00.000Z",
//     start_at: "2020-09-01T00:00:00.000Z",
//     end_at: "2022-12-31T00:00:00.000Z",
//     deleted_at: null,
//     cv: null,
//   },
//   {
//     id: 5,
//     cv_id: 102,
//     title: "Frontend Engineer",
//     company: "InnovateX",
//     city: "Amsterdam",
//     post: "Vue.js Developer",
//     description:
//       "Создание UI-компонентов и оптимизация производительности приложений.",
//     created_at: "2022-01-20T10:15:00.000Z",
//     updated_at: "2024-02-05T09:45:00.000Z",
//     start_at: "2021-05-10T00:00:00.000Z",
//     end_at: null, // текущее место работы
//     deleted_at: null,
//     cv: null,
//   },
//   {
//     id: 6,
//     cv_id: 103,
//     title: "Junior Frontend Developer",
//     company: "WebCraft",
//     city: "Warsaw",
//     post: "JavaScript Developer",
//     description: "Поддержка и разработка клиентских интерфейсов.",
//     // created_at: "2019-11-30T08:20:00.000Z",
//     // updated_at: "2021-08-17T15:10:00.000Z",
//     start_at: "2019-03-15T00:00:00.000Z",
//     end_at: "2020-08-31T00:00:00.000Z",
//     // deleted_at: null,
//     // cv: null,
//   },
// ];

export const publicVacancies: TPublicVacancy[] = [
  {
    id: 1,
    name: "Web-разработчик, web-программист, веб-менеджер, WordPress разработчик",
    salary_from: 80000,
    salary_to: 120000,
    location: "Москва",
    experience: "less-than-1",
    position: "Frontend Developer",
    work_format: "remote",
    employment: "full",
    skills: "React, TypeScript, HTML, CSS",
    responsibilities: "Разработка клиентской части веб-приложений",
    conditions: "Гибкий график, ДМС, обучение",
    description: "Работа над интерфейсами внутренних сервисов компании",
    company_name: "TechCorp",
    company_fullname: "TechCorp Ltd.",
    company_description: "Инновационная IT-компания",
    created_at: "2025-04-30T10:00:00Z",
  },
  {
    id: 2,
    name: "Backend Developer",
    salary_from: 100000,
    salary_to: 150000,
    location: "Санкт-Петербург",
    experience: "from-3-to-5",
    position: "Backend Developer",
    work_format: "office",
    employment: "full",
    skills: "Node.js, PostgreSQL, Redis",
    responsibilities: "Разработка и поддержка API",
    conditions: "Корпоративная библиотека, премии",
    description: "Создание надёжных backend-сервисов",
    company_name: "DataWorks",
    company_fullname: "DataWorks Solutions",
    company_description: "Компания, специализирующаяся на больших данных",
    created_at: "2025-04-29T14:30:00Z",
  },
  {
    id: 3,
    name: "UX/UI Designer",
    salary_from: 90000,
    salary_to: 130000,
    location: "Новосибирск",
    experience: "from-1-to-3",
    position: "UX/UI Designer",
    work_format: "hybrid",
    employment: "full",
    skills: "Figma, UX research, UI kits",
    responsibilities: "Создание прототипов и UI-дизайна",
    conditions: "Оплата конференций, гибкий график",
    description: "Работа в команде с разработчиками и аналитиками",
    company_name: "DesignHub",
    company_fullname: "DesignHub Creative",
    company_description: "Агентство цифрового дизайна",
    created_at: "2025-04-28T09:00:00Z",
  },
  {
    id: 4,
    name: "QA Engineer",
    salary_from: 70000,
    salary_to: 110000,
    location: "Екатеринбург",
    experience: "from-1-to-3",
    position: "QA Engineer",
    work_format: "remote",
    employment: "partial",
    skills: "Jest, Cypress, Manual testing",
    responsibilities: "Тестирование веб-приложений",
    conditions: "Гибкий график, бонусы за баги",
    description: "Функциональное и регрессионное тестирование",
    company_name: "QualitySoft",
    company_fullname: "QualitySoft Inc.",
    company_description: "Лидер в области QA-решений",
    created_at: "2025-04-27T11:00:00Z",
  },
  {
    id: 5,
    name: "DevOps Engineer",
    salary_from: 120000,
    salary_to: 180000,
    location: "Казань",
    experience: "from-3-to-5",
    position: "DevOps Engineer",
    work_format: "hybrid",
    employment: "full",
    skills: "Docker, Kubernetes, CI/CD",
    responsibilities: "Поддержка и автоматизация инфраструктуры",
    conditions: "Удалённая работа, обучение за счёт компании",
    description: "Автоматизация процессов и настройка мониторинга",
    company_name: "InfraTech",
    company_fullname: "InfraTech Systems",
    company_description: "Разработка облачных инфраструктур",
    created_at: "2025-04-26T08:45:00Z",
  },
  {
    id: 6,
    name: "Project Manager",
    salary_from: 100000,
    salary_to: 140000,
    location: "Москва",
    experience: "more-than-5",
    position: "Project Manager",
    work_format: "office",
    employment: "full",
    skills: "Agile, Scrum, управление командами",
    responsibilities: "Управление проектами и координация команды",
    conditions: "Бонусы за завершение проектов",
    description: "Управление ИТ-проектами разной сложности",
    company_name: "ManagePro",
    company_fullname: "ManagePro Group",
    company_description: "Консалтинговая компания",
    created_at: "2025-04-25T10:30:00Z",
  },
  {
    id: 7,
    name: "Mobile Developer",
    salary_from: 110000,
    salary_to: 160000,
    location: "Пермь",
    experience: "from-3-to-5",
    position: "Mobile Developer",
    work_format: "remote",
    employment: "full",
    skills: "Flutter, Dart, Firebase",
    responsibilities: "Разработка мобильных приложений",
    conditions: "Оплата обучения, удалённая работа",
    description: "Создание мобильных решений под Android и iOS",
    company_name: "AppStorm",
    company_fullname: "AppStorm Mobile",
    company_description: "Мобильная разработка под ключ",
    created_at: "2025-04-24T16:00:00Z",
  },
  {
    id: 8,
    name: "System Administrator",
    salary_from: 70000,
    salary_to: 100000,
    location: "Ростов-на-Дону",
    experience: "from-1-to-3",
    position: "System Administrator",
    work_format: "office",
    employment: "full",
    skills: "Linux, Bash, Monitoring",
    responsibilities: "Обслуживание серверов и рабочих станций",
    conditions: "Корпоративная сотовая связь",
    description: "Поддержка IT-инфраструктуры компании",
    company_name: "NetGuard",
    company_fullname: "NetGuard LLC",
    company_description: "Провайдер IT-поддержки",
    created_at: "2025-04-23T13:00:00Z",
  },
  {
    id: 9,
    name: "Business Analyst",
    salary_from: 90000,
    salary_to: 130000,
    location: "Москва",
    experience: "from-3-to-5",
    position: "Business Analyst",
    work_format: "hybrid",
    employment: "full",
    skills: "UML, BPMN, аналитика требований",
    responsibilities: "Сбор и анализ требований заказчиков",
    conditions: "ДМС, тренинги",
    description: "Работа в команде разработки над крупными проектами",
    company_name: "BizLogic",
    company_fullname: "BizLogic Consulting",
    company_description: "Консалтинг и разработка решений",
    created_at: "2025-04-22T09:15:00Z",
  },
  {
    id: 10,
    name: "Data Analyst",
    salary_from: 85000,
    salary_to: 125000,
    location: "Нижний Новгород",
    experience: "less-than-1",
    position: "Data Analyst",
    work_format: "remote",
    employment: "full",
    skills: "SQL, Python, Tableau",
    responsibilities: "Анализ данных, построение отчётов",
    conditions: "Гибкий график, наставничество",
    description: "Работа с большими данными для отчётности",
    company_name: "DataLine",
    company_fullname: "DataLine Analytics",
    company_description: "Платформа аналитики данных",
    created_at: "2025-04-21T17:20:00Z",
  },
  {
    id: 11,
    name: "Product Manager",
    salary_from: 120000,
    salary_to: 170000,
    location: "Москва",
    experience: "from-3-to-5",
    position: "Product Manager",
    work_format: "hybrid",
    employment: "full",
    skills: "Product vision, Agile, коммуникации",
    responsibilities: "Разработка стратегии продукта и его развитие",
    conditions: "Опцион, гибкий график",
    description: "Работа с командой разработки и маркетинга",
    company_name: "InnovateX",
    company_fullname: "InnovateX Global",
    company_description: "Разработка цифровых продуктов",
    created_at: "2025-04-20T12:00:00Z",
  },
  {
    id: 12,
    name: "Technical Writer",
    salary_from: 60000,
    salary_to: 90000,
    location: "Воронеж",
    experience: "from-1-to-3",
    position: "Technical Writer",
    work_format: "remote",
    employment: "partial",
    skills: "Markdown, API Docs, Git",
    responsibilities: "Создание технической документации",
    conditions: "Гибкий график",
    description: "Подготовка мануалов, справок и API-описаний",
    company_name: "DocuSoft",
    company_fullname: "DocuSoft Technologies",
    company_description: "Автоматизация и документация",
    created_at: "2025-04-19T11:45:00Z",
  },
  {
    id: 13,
    name: "Machine Learning Engineer",
    salary_from: 140000,
    salary_to: 200000,
    location: "Новосибирск",
    experience: "from-3-to-5",
    position: "ML Engineer",
    work_format: "remote",
    employment: "full",
    skills: "Python, TensorFlow, Scikit-learn",
    responsibilities: "Разработка и обучение моделей",
    conditions: "GPU-серверы, конференции",
    description: "Работа над продуктами на базе ИИ",
    company_name: "AI Stream",
    company_fullname: "AI Stream Labs",
    company_description: "Решения на основе машинного обучения",
    created_at: "2025-04-18T16:30:00Z",
  },
  {
    id: 14,
    name: "HR Specialist",
    salary_from: 70000,
    salary_to: 100000,
    location: "Калуга",
    experience: "less-than-1",
    position: "HR Specialist",
    work_format: "office",
    employment: "full",
    skills: "HRIS, рекрутинг, интервью",
    responsibilities: "Подбор и адаптация сотрудников",
    conditions: "Корпоративные мероприятия",
    description: "Ведение HR-процессов компании",
    company_name: "PeopleFirst",
    company_fullname: "PeopleFirst HR Group",
    company_description: "Эксперты в подборе персонала",
    created_at: "2025-04-17T10:00:00Z",
  },
  {
    id: 15,
    name: "SMM Specialist",
    salary_from: 50000,
    salary_to: 80000,
    location: "Сочи",
    experience: "less-than-1",
    position: "SMM Specialist",
    work_format: "remote",
    employment: "partial",
    skills: "Instagram, TikTok, креативность",
    responsibilities: "Ведение социальных сетей",
    conditions: "Свободный график",
    description: "Создание контента и продвижение бренда",
    company_name: "MediaWave",
    company_fullname: "MediaWave Digital",
    company_description: "Креативное агентство полного цикла",
    created_at: "2025-04-16T09:30:00Z",
  },
  {
    id: 16,
    name: "Content Manager",
    salary_from: 60000,
    salary_to: 95000,
    location: "Томск",
    experience: "from-2-to-4",
    position: "Content Manager",
    work_format: "hybrid",
    employment: "full",
    skills: "CMS, SEO, копирайтинг",
    responsibilities: "Управление контентом сайта",
    conditions: "ДМС, обучение",
    description: "Размещение и редактирование контента",
    company_name: "WebEdge",
    company_fullname: "WebEdge Studio",
    company_description: "Веб-студия и маркетинг",
    created_at: "2025-04-15T15:15:00Z",
  },
  {
    id: 17,
    name: "Tech Support Engineer",
    salary_from: 50000,
    salary_to: 85000,
    location: "Иркутск",
    experience: "less-than-1",
    position: "Support Engineer",
    work_format: "office",
    employment: "full",
    skills: "Helpdesk, Jira, коммуникации",
    responsibilities: "Поддержка пользователей",
    conditions: "Корпоративное обучение",
    description: "Решение технических запросов клиентов",
    company_name: "SupportLine",
    company_fullname: "SupportLine Systems",
    company_description: "Техническая поддержка 24/7",
    created_at: "2025-04-14T11:00:00Z",
  },
  {
    id: 18,
    name: "Security Analyst",
    salary_from: 110000,
    salary_to: 160000,
    location: "Москва",
    experience: "from-3-to-5",
    position: "Security Analyst",
    work_format: "office",
    employment: "full",
    skills: "SIEM, ISO 27001, SOC",
    responsibilities: "Мониторинг и реагирование на инциденты",
    conditions: "Компенсация сертификаций",
    description: "Информационная безопасность корпоративных систем",
    company_name: "CyberDef",
    company_fullname: "CyberDefence Group",
    company_description: "Информационная безопасность и аудит",
    created_at: "2025-04-13T18:00:00Z",
  },
  {
    id: 19,
    name: "Data Engineer",
    salary_from: 130000,
    salary_to: 190000,
    location: "Калининград",
    experience: "from-3-to-5",
    position: "Data Engineer",
    work_format: "remote",
    employment: "full",
    skills: "ETL, BigQuery, Python",
    responsibilities: "Проектирование хранилищ данных",
    conditions: "Удалённая работа, развитие",
    description: "Разработка решений для аналитики данных",
    company_name: "DataShift",
    company_fullname: "DataShift Technologies",
    company_description: "Разработка решений для обработки данных",
    created_at: "2025-04-12T09:00:00Z",
  },
  {
    id: 20,
    name: "Sales Manager",
    salary_from: 70000,
    salary_to: 100000,
    location: "Краснодар",
    experience: "from-1-to-3",
    position: "Sales Manager",
    work_format: "office",
    employment: "full",
    skills: "CRM, переговоры, продажи",
    responsibilities: "Продажа продуктов компании",
    conditions: "Приятная атмосфера в офисе",
    description: "Привлечение и работа с клиентами",
    company_name: "SalesPlus",
    company_fullname: "SalesPlus Corporation",
    company_description: "Компания по продажам бизнес-услуг",
    created_at: "2025-04-11T08:45:00Z",
  },
];
