import { usePathname } from "next/navigation";
import { getBreadcrumbMapping } from "../config/breadcrumbaMapping";
import { IBreadcrumbPattern } from "../config/types";
import { pathToRegexp, match } from "path-to-regexp"
import { decodeSegment } from "@/shared/lib/encodeSegments";

type DefineBreadcrumbsPaths = (breadcrumbsMapping: IBreadcrumbPattern[], pathname: string) => { href: string, label: string | React.ReactNode, isLink: boolean }[]

const HIDDEN_SEGMENTS = ['all']

type BreadcrumbsPaths = ReturnType<DefineBreadcrumbsPaths>

/**
 * Generates an array of breadcrumb items based on the current pathname and the breadcrumb mapping.
 *
 * It splits the pathname into hierarchical segments and attempts to match each one
 * against provided breadcrumb patterns using `path-to-regexp`. If a match is found,
 * it uses the corresponding `handler` function to generate a label for the breadcrumb.
 *
 * @param breadcrumbsMapping - An array of breadcrumb route definitions. Each definition includes:
 *    - `pattern`: A path-to-regexp compatible pattern string for matching.
 *    - `handler`: A function that returns a React node or string label for the matched path.
 *    - `isLink`: A boolean indicating if the breadcrumb should be rendered as a link.
 *
 * @param pathname - The current URL pathname (e.g., `/dashboard/vacancies/123`). Used to resolve each breadcrumb level.
 *
 * @returns An array of breadcrumb objects where each object contains:
 *    - `href`: A resolved partial path (e.g., `/dashboard`, `/dashboard/vacancies`).
 *    - `label`: The display label (string or JSX) generated by the handler.
 *    - `isLink`: A flag indicating whether the breadcrumb should be a clickable link.
 */

const defineBreadcrumbsPaths: DefineBreadcrumbsPaths = (breadcrumbsMapping, pathname: string | null) => {
  const breadcrumbsPaths: BreadcrumbsPaths = [];

  if (pathname) {
    // Get path segments. If it's the root pathname, we use [''], otherwise we split the pathname by '/' to build hierarchical breadcrumb paths.
    let pathSegments;
    if (pathname === '/') pathSegments = ['']
    else {
      pathSegments = pathname.split('/');
    }


    // Iterate through each path segment to build breadcrumb paths and match them with patterns.
    pathSegments.forEach((segment, i) => {
      // Create the current path by joining segments up to the current index.
      const currentPath = `/${pathSegments.slice(0, i + 1).join('/')}`.replace(/^\/+/, '/');
      //check if segment is in the hidden list to exclude it from the breadcrumbsPaths
      const isHiddenSegment = HIDDEN_SEGMENTS.includes(segment)

      // Find a matching pattern in the breadcrumbs mapping for the current path.
      const matchingMaping = breadcrumbsMapping.find((el) => {
        const regexp = pathToRegexp(el.pattern).regexp
        return regexp.test(currentPath)
      }
      );
      // If a matching pattern is found, add it to the breadcrumb paths.
      if (matchingMaping && !isHiddenSegment) {
        //using path-to-regexp's method match to extract parameters from the current path
        const matchParams = match(matchingMaping.pattern, { decode: decodeSegment })(currentPath)
        const params = matchParams ? matchParams.params : null

        breadcrumbsPaths.push({
          href: currentPath,
          label: matchingMaping.handler(params),
          isLink: matchingMaping.isLink
        })
      }
    });
  }
  return breadcrumbsPaths;
};

const useBreadcrumbs = (tenant: string) => {
  const pathname = usePathname() as string

  // Get breadcrumbs mapping based on current tenat
  const currentMapping = getBreadcrumbMapping(tenant)

  return defineBreadcrumbsPaths(currentMapping, pathname)
}

export default useBreadcrumbs;
